use_frameworks!

platform :ios, '10.0'

target 'FlexUI_Example' do
  pod 'FlexUI', :path => '../'
  pod 'FlexLayout', '~> 1.3'
  pod 'PinLayout', '~> 1.10.0'

  target 'FlexUI_Tests' do
    inherit! :search_paths
  end
end
